### ISSUE TITLE
Gettext action should fail if meson returns non 0 exit code.

### ISSUE THREAD

**Issue by arshubham** [elementary/actions#21]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Action should fail if meson returns non 0 exit code. I got this issue with gettext action. Might affect others too.

### Expected behavior
Action should fail.

### Additional context

The following action failed to update translation template due to `meson.build:37:6: ERROR:  Script or command 'meson/post_install.py' not found or not executable`, however Action completed with a success response.
https://github.com/arshubham/cipher/commit/cfb48b0d1ff2457b9462878dc5c79971e876f8ef/checks?check_suite_id=313032511

**Comment by ryonakano** [comment]
I tested on my repository and guess it correctly fails when this error happens. See: https://github.com/ryonakano/konbucase/runs/673186757

**Comment by ryonakano** [comment]
I'll close this issue because it seems to be fixed (see my previous comment). Reopen if it persists.
