### ISSUE TITLE
Release: Don't assume changelog is just a list

### ISSUE THREAD

**Issue by cassidyjames** [elementary/actions#22]
i.e. see https://github.com/elementary/videos/releases/tag/2.7.0; it was originally created as 

>* New features:
>* Option to automatically play next videos
>* Navigate the playlist with the keyboard
>* Add a button to clear the playlist
>* Show audio track language in settings
>* Show playlist item titles in their tooltips
>* Other updates:
>* Show an error for unsupported files
>* Fix disappearing cursor on headerbar
>* Hide seekbar preview when switching windows with Alt + Tab
>* Translation updates

I manually edited it to read

>New features:
>
>* Option to automatically play next videos
>* Navigate the playlist with the keyboard
>* Add a button to clear the playlist
>* Show audio track language in settings
>* Show playlist item titles in their tooltips
>
>Other updates:
>
>* Show an error for unsupported files
>* Fix disappearing cursor on headerbar
>* Hide seekbar preview when switching windows with Alt + Tab
>* Translation updates

… which better matches the appdata

https://github.com/elementary/videos/blob/81cd005eb4e3fbdd8acd07adbbfed5f3bb83aa04/data/io.elementary.videos.appdata.xml.in#L63-L81

**Comment by kgrubb** [comment]
resolved via https://github.com/elementary/actions/pull/23
