### ISSUE TITLE
Release: Exclude duplicate lines in Debian changelog

### ISSUE THREAD

**Issue by cassidyjames** [elementary/actions#51]
The Release action should not duplicate lines in any given release's Debian changelog. It looks like we can filter the commits in bash somewhere around here:

https://github.com/elementary/actions/blob/5d07d8735bf665e76c3409a281faa38967b5d810/release/entrypoint.sh#L102-L118

For an example of duplicate lines in a changelog, see: https://github.com/elementary/appcenter/blob/d8d1d80affb6f440d71a896f2fae63772151fb06/debian/changelog#L24-L25

**Comment by pushp1997** [comment]
Hi, I would like to work on this. Can you please assign it to me?

So, only the duplicate lines are to be removed right? Am I correct?

**Comment by garg-saurav** [comment]
Hi @cassidyjames I have removed the duplicate lines but the link points to a detached head. Can you tell me which branch to push to or should I create a new branch (in which case any suggested name?)

**Comment by cassidyjames** [comment]
@pushp1997 and @garg-saurav sorry about the delay in responding. Let me clarify this issue:

We have a `release` action in **this** repository. I would like the GitHub Action to be updated to not spit out duplicate lines in the generated Debian changelog.

The linked example is an example output from a different repository that is using this GitHub Action, and exhibiting the behavior I would like to fix in this action.
