### ISSUE TITLE
Releases: Exclude `Update file.extension` commits

### ISSUE THREAD

**Issue by cassidyjames** [elementary/actions#52]
See: https://github.com/elementary/appcenter/blob/d8d1d80affb6f440d71a896f2fae63772151fb06/debian/changelog#L117

**Comment by garg-saurav** [comment]
Taking this up

**Comment by garg-saurav** [comment]
Hi @cassidyjames Do you want to exclude commits like `Update flatpak.vapi (#1122)` as well or only commits like `Update something.extension`?

**Comment by cassidyjames** [comment]
@garg-saurav sorry, this got buried. If it has `(#...)`, it means it was a pull request and not a commit to master… so I think leaving it is fine.
