### ISSUE TITLE
Generate translation files when strings change

### ISSUE THREAD

**Issue by danirabbit** [elementary/actions#6]
Something we're currently doing manually is follow-up commits that run `ninja projectname-pot` and `ninja projectname-update-po`.

It would be nice if we could have an automation that would automatically run these (and their `extra` counterparts) on commit to master and then commit and push the results if there have been string changes.

We previously discussed in slack that we can determine if there are significant changes because lines we don't care about are all prefixed with a `#` char

**Comment by davidmhewitt** [comment]
Some useful info on filtering the diff of `.pot` files here:
https://medium.com/@rkz_io/making-a-clutter-free-git-diff-on-gettext-translation-files-9c0c1bb1d8aa

**Comment by kgrubb** [comment]
One thing to note is that a few projects don't have the right project name for their `ninja projectname-pot`. We'll probably need to get app names cleaned up a bit during this process also.
