### ISSUE TITLE
gettext: Don't require deb-packaging branch existing

### ISSUE THREAD

**Issue by ryonakano** [elementary/actions#63]
AppCenter is going to switch its packaging system from Debian Packaging to Flatpak. So it would be nice if Gettext Actions no longer requires existence of `deb-packaging` branch.

It seems like required because we use it to install dependencies listed in `debian/control`

**Comment by tintou** [comment]
Fixed by https://github.com/elementary/actions/commit/d610b15f63bc93d705acd46305456bff912bbfb7
